/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/WinGoldView.lh
 */
export class WinGoldViewRTBase extends Laya.Box {
    public btnHome!: Laya.Button;
    public btnAgain!: Laya.Button;
}

