/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/WinView.lh
 */
export class WinViewRTBase extends Laya.Box {
    public lblTitle!: Laya.Label;
    public btnClose!: Laya.Button;
    public btnContinue!: Laya.Button;
}

