/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/PauseView.lh
 */
export class PauseViewRTBase extends Laya.Box {
    public imgNewRecord!: Laya.Image;
    public lblCurrentScore!: Laya.Label;
    public lblHistoryScore!: Laya.Label;
    public btnResume!: Laya.Button;
    public btnMainMenu!: Laya.Button;
    public btnRestart!: Laya.Button;
}

