/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/HUD.lh
 */
export class HudViewRTBase extends Laya.Box {
    public btnBack!: Laya.Button;
    public lblDistance!: Laya.Label;
}

