/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/HUD.lh
 */
export class HudViewRTBase extends Laya.Box {
    public btnBack!: Laya.Button;
    public btnScroll!: Laya.Button;
    public progress!: Laya.ProgressBar;
    public imgHead!: Laya.Image;
    public imgAward!: Laya.Image;
    public boxMask!: Laya.Box;
    public btnContinue!: Laya.Button;
    public lblDistance!: Laya.Label;
}

