/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/SkinItem.lh
 */
export class SkinItemRTBase extends Laya.Box {
    public imgBg!: Laya.Image;
    public imgAvatarBg!: Laya.Image;
    public btnUnlock!: Laya.Button;
    public imgVideo!: Laya.Image;
    public btnAdventure!: Laya.Button;
    public imgAdventuring!: Laya.Image;
}

