/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/SkinItem.lh
 */
export class SkinItemRTBase extends Laya.Box {
    public imgBg!: Laya.Image;
    public lblUsing!: Laya.Label;
    public btnUnlockOrUse!: Laya.Button;
    public imgVideo!: Laya.Image;
}

