/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/SkinView.lh
 */
export class SkinViewRTBase extends Laya.Box {
    public lblTitle!: Laya.Label;
    public list!: Laya.List;
    public btnClose!: Laya.Button;
}

