/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/LoadingView.lh
 */
export class LoadingViewRTBase extends Laya.Box {
    public progress!: Laya.ProgressBar;
    public lblProgress!: Laya.Label;
}

