/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Prefab2D.lh
 */
export class MainViewRuntimeBase extends Laya.Box {
    public btnPlay!: Laya.Button;
}

