/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefabs/views/Help.lh
 */
export class HelpViewRTBase extends Laya.Box {
    public btnClose!: Laya.Button;
}

