/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/Help.lh
 */
export class HelpViewRTBase extends Laya.Box {
    public lblDesc!: Laya.Label;
    public btnClose!: Laya.Button;
}

