/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/views/MainView.lh
 */
export class MainViewRTBase extends Laya.Box {
    public boxLogo!: Laya.Box;
    public btnSkin!: Laya.Button;
    public btnPractice!: Laya.Button;
    public btnHelp!: Laya.Button;
    public btnPlay!: Laya.Button;
}

